### ISSUE TITLE
Misspelled Greek word under <entry n="Ἀββά|G5">

### ISSUE THREAD

**Issue by petervdschelde** [translatable-exegetical-tools/Abbott-Smith#100]
used in the phrase <foreign xml:lang="grc">Ἀ. ὁ παήρ</foreign>,

should be:

used in the phrase <foreign xml:lang="grc">Ἀ. ὁ πα**τ**ήρ</foreign>,

Saw this at the first look in the xml. How is the overall quality of the text? 
If I see such an error immetiade I start to doubt on quality. Normally I dod not see these kind of OCR-errors quickly.

**Comment by destatez** [comment]
Good find. I’m probably the only one left around who was part of the team that reviewed and corrected the OCR against the original. I’m sorry that you are doubting the quality. We put a ton of time in that review, but then again, we’re just humans.
