### ISSUE TITLE
a number of issues I hit with the entry/@n values

### ISSUE THREAD

**Issue by jtauber** [translatable-exegetical-tools/Abbott-Smith#11]
Stray iota subscript
-γαστήρͅ|G1064
+γαστήρ|G1064

Stray semicolon
-διαβλέπω;|G1227
+διαβλέπω|G1227

I presume the n attribute shouldn't contain the hyphens (but not sure intention)
-ἐκ-κρέμαννυμι
+ἐκκρέμαννυμι

Stray period
-Ἑσρώμ.|G2074|Ἑσρώμ
+Ἑσρώμ|G2074|Ἑσρώμ

Not sure if parenthetical μήν should be in n attribute
-ἦ(μήν)|G2229
+ἦ|G2229

Stay period
-ὅπως.|G3704
+ὅπως|G3704

OCR problem?
-πυνθώ'ομαι|G4441
+πυνθάνομαι|G4441

**Comment by dowens76** [comment]
Thanks for this report. I have made the fixes and committed them.
