### ISSUE TITLE
Missing entry - αλλαχου

### ISSUE THREAD

**Issue by pdurusau** [translatable-exegetical-tools/Abbott-Smith#12]
Page 21 missing entry between <entry n="ἀλλαχόθεν|G237"> and <entry n="ἀλληγορέω|G238">, should be: αλλαχου

This will impact the numbering of entries G238 and following.

**Comment by dowens76** [comment]
Created the entry. Thankfully there is no entry in Strong's, so this is not a problem for numbering. Thanks for the report.
