### ISSUE TITLE
Remove soft hyphens G262, G263

### ISSUE THREAD

**Issue by pdurusau** [translatable-exegetical-tools/Abbott-Smith#14]
<entry n="ἀμαράντινος|G262">
...
<sense>of amaranth (Inscr.); hence un­fading: <ref osisRef="1Pet.5.4">I Pe 5:4</ref>.†</sense>

suspect the hyphen in un-fading was soft hyphen - correct to unfading

<entry n="ἀμάραντος|G263">
...
 <sense>un­fading (whence <foreign xml:lang="grc">ὁ ἀ.</foreign>, the amaranth, an unfading flower): <ref osisRef="1Pet.1.4">I Pe 1:4</ref> (cf. MM, <emph>VGT</emph>, s.v.).†</sense>

suspect the hyphen in un-fading was soft hyphen - correct to unfading

**Comment by dowens76** [comment]
Yes, fixed. Thanks.
