### ISSUE TITLE
Soft hyphen <entry n="ἀνακαίνωσις|G342">

### ISSUE THREAD

**Issue by pdurusau** [translatable-exegetical-tools/Abbott-Smith#17]
<entry n="ἀνακαίνωσις|G342">

<emph>SYN.</emph>: <foreign xml:lang="grc" n="G3824">παλινγενεσία</foreign>, in NT, new birth, of which <foreign xml:lang="grc">ἀ.</foreign> is the conse-­quent renewal

suspect soft-hypher at conse-quent -> consequent

**Comment by dowens76** [comment]
Yes, fixed. Thanks. You can feel free to edit master, if you are comfortable doing that. Let me know if you want to, and I can add you to the project.
