### ISSUE TITLE
Beta (all A-S pages containing the letter beta)

### ISSUE THREAD

**Issue by cpresson** [translatable-exegetical-tools/Abbott-Smith#20]
@drew-curley 
- [ ] Page 73
- [ ] Page 74
- [ ] Page 75
- [ ] Page 76
- [ ] Page 77
- [ ] Page 78
- [ ] Page 79
- [ ] Page 80
- [ ] Page 81
- [ ] Page 82
- [ ] Page 83
- [ ] Page 84
- [ ] Page 85
- [ ] Page 86

**Comment by drew-curley** [comment]
Yes, I am hoping to be done tomorrow afternoon with this list, and then sync it to github

**Comment by cpresson** [comment]
Great!

 

I don’t have permissions to assign the issue to you yet, but this is how (i.e., using issues) I want to track progress with the project.

 

Thanks!

 

Chapel
