### ISSUE TITLE
ποία - missing entry

### ISSUE THREAD

**Issue by jonathanrobie** [translatable-exegetical-tools/Abbott-Smith#3]
My paper copy has a separate entry for ποία that is missing in the online version.

**Comment by dardosordi** [comment]
That is very likely to happen in some pages we haven't manually check yet. I'll take a look into that and try to fix it. Thanks.

**Comment by jonathanrobie** [comment]
Thanks - I'll keep reporting things I don't find.

**Comment by dowens76** [comment]
I added this entry just to clear out the issues.
