### ISSUE TITLE
ἔπειτα missing entry 

### ISSUE THREAD

**Issue by jonathanrobie** [translatable-exegetical-tools/Abbott-Smith#4]
The entry for ἔπειτα  seems to be missing.

**Comment by dowens76** [comment]
Thanks, will work on it.

**Comment by dowens76** [comment]
Is this entry "ἔπειτα, adv. of sequence"? If so, we just simply did not have the acute accent over the first epsilon. I fixed that. If not, let me know. I will mark this closed unless I hear back from you.
