### ISSUE TITLE
Hot-Links missing for some classes of word references

### ISSUE THREAD

**Issue by destatez** [translatable-exegetical-tools/Abbott-Smith#66]
There appear to be 3 classes of instances where hot-links (XML <ref...></ref> tag-pairs) should be present for links to other words in the XML file:
1. The use of the character "<" for "derived from" should have the following word(s) hot-linked
2. The word(s) following the "SYN" keyword should be hot-linked
3. (This needs a confirmation from Todd) The use of the character "=" for "equal to" with following Greek, and not English, should have those following word(s) hot-linked

For each of these cases, only the referenced words that exist in this XML should be hot-linked, otherwise they should NOT BE modified to have the XML <ref...></ref> tag-pair.

This could be an automated task by an XML-smart tool to check for compliance, and to update with the tag-pair, where needed

**Comment by toddlprice** [comment]
Yes, I agree with all this including #3.

**Comment by destatez** [comment]
Chuck

  Is this something you can pick up with your XML-smart tool/scripts or are you up to your eyeballs? I haven't seen/heard anything from Patrick for a while. Has he moved on to other things?

Dave

**Comment by cbearden** [comment]
Hi Dave,

I think this is doable, but like most complex changes of this sort it
should probably be reviewed by a human editor. The first step I would take
would be analysis: (a) can I identify the relevant cases with the Greek
words to be linked; (b) for how many of the candidate links can I find
targets within the document? (c) what is the best markup to specify the
link?

Sorry I haven't had much time the past three or four days. If you haven't
worked up the Appendix A, I think I have an approach that will get it
mostly right to start with. I just haven't had time to implement yet.

I haven't heard from Patrick either. My only interaction with him has been
the recent discussion in the Google Group.

All the best,
Chuck

**Comment by destatez** [comment]
Chuck

  We could do a divide and conquer. I can search for the 3 cases listed in the Issue. I already have the "entries" in a hash, that I can update after the latest Pull Request, so I could generate a report for each instance that has an entry link in the doc and which needs to be updated. This will take  some perl "re", but that's not that hard, I mess with "re" a lot. In terms of the update, I was thinking of following the current scheme which has the referenced "entry" surrounded by a <ref> tag-pair. See below for `στρατοπέδαρχος`
`(&lt; <ref><foreign xml:lang="grc">στρατόπεδον</foreign></ref>, <ref><foreign xml:lang="grc">ἄρχω</foreign></ref>)`

 Relative to the appendix(s), why don't you work up the schema that you talked about. I think that it is the right answer. Did you see my questions on that topic in the Google group discussion?

Dave

**Comment by destatez** [comment]
Todd

  I have some questions on how to handle the SYN. references. Below are several examples, where I have questions about what ought to be and what ought not to be "referenced".
The possible combinations are almost endless, so could you define some guidelines (rules) for what to tag and what not to tag?

For the first, ἀθέμιτος, should the v.s. be treated as "for example" with the subsequent grc word ἄθεσμος tagged with <ref>...</ref>? 
Should the 2nd, ψυχή, be processed likewise for νοῦς, and also tag the 2nd, πνεῦμα, and 3rd, ψυχικός, grc words with <ref>...</ref>? 
The 3rd through 5th have different forms of q.v. following the 1st instance. 
Should the 3rd, ἄδολος, have ἀκέραιος and its 2nd, ἄκακος, and 3rd, ἁπλοῦς, instances tagged?
Should the 4th, ἁγνίζω, have καθαρίζω and the instance, ἁγνός, following the v.s. tagged?
Should the 5th, ἀγρυπνέω, have γρηγορέω and the instance, νήφω, tagged?
Should the 6th, ἀγάπη, have φιλία as well as the instance following the v.s., ἀγαπάω tagged?
Should the 7th, ἀγαθός, have only καλός and δίκαιος tagged?

```
1) ἀθέμιτος	<re><emph>SYN.</emph>: v.s. <foreign xml:lang="grc">ἄθεσμος</foreign>.</re>
2) ψυχή			<re><emph>SYN.</emph>: v.s. <foreign xml:lang="grc"><ref>νοῦς</ref>, <ref>πνεῦμα</ref>, <ref>ψυχικός</ref></foreign>, and cf....
3) ἄδολος		<re><emph>SYN.</emph>: <foreign xml:lang="grc">ἀκέραιος</foreign> (q.v.), <foreign xml:lang="grc">ἄκακος</foreign>, <foreign xml:lang="grc">ἁπλοῦς</foreign>.</re>
4) ἁγνίζω		<re><emph>SYN.</emph>: <foreign xml:lang="grc">καθαρίζω</foreign>, q.v. (and v.s. <foreign xml:lang="grc">ἁγνός</foreign>).</re>
5) ἀγρυπνέω	<re><emph>SYN.</emph>: <foreign xml:lang="grc">γρηγορέω</foreign>, q.v.; <foreign xml:lang="grc">νήφω</foreign>, associated with <foreign xml:lang="grc">γ.</foreign> in...
6) ἀγάπη			<re><emph>SYN.</emph>: <foreign xml:lang="grc">φιλία</foreign>. <foreign xml:lang="grc">ἀ.</foreign>, signifying properly (v.s. <foreign xml:lang="grc">ἀγαπάω</foreign>) ...
7) ἀγαθός		<re><emph>SYN.</emph>: <foreign xml:lang="grc">καλός</foreign>, <foreign xml:lang="grc">δίκαιος</foreign>. <foreign xml:lang="grc">κ.</foreign> properly refers to ...
```

**Comment by toddlprice** [comment]
Since v.s. is vide sub. ("see below") and q.v. is quod vice ("which see"), all the words listed under SYN. should be made into hot links which go to the entries for those words. This includes the abbreviations for the words, such as:
in #5.  γ. should be a hot link to γρηγορέω.
in #7, κ. should be a hot link to καλός, , δ. should be a hot link to δίκαιος, etc.

**Comment by destatez** [comment]
Below is a link to a prototype report for this issue which identifies the instances for all 3 categories where references to Entries should be tagged with the <ref> tag-pair. I also identify any instances where an existing <ref> is invalid because the tagged word is not in A-S. There are also two subcategories under SYN where analysis is required for potential XML modification and/or insertion of the <ref> tag-pair. I will rerun this when all editing of the main body is complete. Please comment on whether you think I have covered the bases regarding scope of the report and/or anything about the format that needs correction and/or clarification.
[A_S_Reference_Analysis.txt](https://github.com/translatable-exegetical-tools/Abbott-Smith/files/664435/A_S_Reference_Analysis.txt)

**Comment by toddlprice** [comment]
This looks correct for me except for:
1) is = the same as EQV? If so, why do some entries list = and some as EQV?
2) in the second section, there are many abbreviated words that SHOULD be made into entries. E.g., line  282 has "Entry ἀγαθός and SYN κ". The κ is an abbreviation for  καλός and so should be linked to the entry for  καλός. Many of the entries fall into that category (i.e. the abbreviations should be linked to an entry).

**Comment by destatez** [comment]
The EQV are instances where there is an "<" (&lt;) in A-S. The " = " are instances where there is an "=" in A-S. The second section where I have identified abbreviations will need manual updates to the XML to specify the word of the abbreviation, and then to tag it. This requires manual analysis and can not be automated.

In my estimation, even the instances in the 1st section should be manually tagged. Automation would be a little difficult with all the variations of interspersed letters and words and prone to error.

**Comment by toddlprice** [comment]
OK. Sounds good!

**Comment by destatez** [comment]
I experimented with my previous file by starting to do edits on my local XML file. What I realized was having the multiple lists was not the way to go. I have combined all of the "classes" of type of changes needed to the XML with the 3 different forms that require the reference tagging. The attached is the report for only the letter alpha. The total list has over 1800 lines.
[A_S_Reference_Analysis_V4-Alpha_only.txt](https://github.com/translatable-exegetical-tools/Abbott-Smith/files/672120/A_S_Reference_Analysis_V4-Alpha_only.txt)

**Comment by cbearden** [comment]
Is the idea to use the 'target' attribute of 'ref' to refer to the target
entry? There's an example of 'ref/@target', on line 1478. Is that our model?

This is the example I found:
<ref target="#ἀγαθοεργέω"><foreign xml:lang="grc">ἀγαθοερ-</foreign></ref>
(q.v.)

**Comment by destatez** [comment]
Chuck

I'm not sure that I understand the context of what you are asking. For the
'<', '=', and SYN what HAS been done is to simply wrap the 'referenced'
word with '<ref>....<\ref>' so that it is a simple 'hotlink' that can be
followed. I know of no other plan to further mark these referenced words.

Dave

**Comment by BramvandenHeuvel** [comment]
Hey Chuck
I notice that a word following s.v. (and q.v.) needs to be ref'ed if it is in a SYN section, but what about the entries that just have "word v.s. word", should the second word also be ref'ed?

**Comment by destatez** [comment]
Bram

  Scan down the message trail of this issue and see Todd's comments about
s.v. and q.v. From his comments the answer would be both.

Dave

**Comment by destatez** [comment]
I have put the full report for candidate <ref> tags in a gist: https://gist.github.com/destatez/ead063a3b2b2d1d4670243dc745fb267#file-a_s_reference_analysis_v4-txt

**Comment by cbearden** [comment]
Hi Dave,

It sounds like you were going to let your downstream software construct the
hot-link from the contents of the <ref> tag; I was assuming that the <ref>
tag would bear an attribute that points more exactly to the target entry,
in line with the example I found of 'ref' with the 'target' attribute. This
is analogous to the treatment of scripture references, where the 'ref' tag
bears the 'osisRef' attribute.

Thus, where the form of the word that appears in the text isn't exactly the
same as the head-word in the target entry, the text wouldn't have to be
modified to disambiguate the link. <ref> by itself can tell you that a link
needs to be made, but unless the contents of the <ref> unambiguously tell
you what the target of the link is, you can't link to something. Am I
making any sense?

Chuck

**Comment by destatez** [comment]
Chuck

   I do not understand "unless the contents of the <ref> unambiguously tell
you what the target of the link is, you can't link to something" With the
<ref> tag-pair around a Greek word, it is treated as a hot-link within the
XML file. I "follow" each one I create to make sure that the other Entry is
present. Yes, there is nothing in the XML which identifies what the ref is
all about, but I was addressing only the ability to hot-link, which is what
the end-user is most concerned about.

Dave

**Comment by cbearden** [comment]
Hi Dave,

I think I understand what you have in mind. A question to illustrate where
I'm coming from:

In the case of the 'ἀγαθός' SYN section, if you tag the 'κ.' with a bare
<ref>, like so:

  <ref><foreign xml:lang="grc">κ.</foreign></ref>

what will this hotlink to? There is no indication in the markup which
headword beginning with 'κ' will point. In the case that the <foreign> tag
encloses a word that matches exactly the form of a unique headword, there's
no problem. But in this case, there is ambiguity. I was assuming (probably
wrongly) that there would be an attribute like the 'href' for the <a>
element to provide the information for the link.

If I'm not making sense, I'll drop the issue.

Chuck

**Comment by destatez** [comment]
Chuck

  You have a very good point, and one that I brought up to Todd. See his answer to a related instance in: https://github.com/translatable-exegetical-tools/Abbott-Smith/issues/66#issuecomment-268749055 . For all of these cases my report identifies these single letters and requests analysis for manual update.

Dave
