### ISSUE TITLE
Miscellaneous simple markup problems

### ISSUE THREAD

**Issue by cbearden** [translatable-exegetical-tools/Abbott-Smith#69]
These are problems too minor each to have their own issues. I could easily fix them, but I don't want to complicate things during merges from the section editors. Would it make sense for them to check for and implement the changes?

1. Well-formedness error: at line 55272 there is an unescaped ampersand ("&" should be "&amp;").
1. There are several `<ref>` elements with the attribute `osisref`; it should be `osisRef`, with an upper-case "R". This is a validity error against the teiP5osis.2.5.0.xsd schema.
1. The element for sense "2" of "ἐπιούσιος" should probably enclose the following lettered sub-senses, but it is closed before "(a)".
1. There are three instances of an extra greater-than (">") following the closing greater-than of a tag (lines 5926, 10708, 35047).

**Comment by destatez** [comment]
Chuck

  There are only 4 or 5 letters (Issues thru #50) remaining that are being edited. I think that we need Chapel to either assign this to an editor, when all 1st-pass edits are complete, or have her tag this as an issue that one of the editors needs to self-assign.

Dave

**Comment by cbearden** [comment]
Sounds good. These changes should  take no more than 15 minutes.

**Comment by destatez** [comment]
Chuck updated these entries in one of his PRs.
