### ISSUE TITLE
'foreign[@n]' tags an English word referring to another Greek entry

### ISSUE THREAD

**Issue by cbearden** [translatable-exegetical-tools/Abbott-Smith#7]
In the entry for 'ἀνθ-υπατεύω', the English word 'word' is tagged with `foreign`, probably so as to to supply it with an `n` attribute that refers to another entry.

```
<entry n="ἀνθυπατεύω|G445">
  <note type="occurrencesNT">1</note>
  <form>*† <orth>ἀνθ-υπατεύω</orth></form>
<etym>
  <seg type="derivation">(see next <foreign xml:lang="grc" n="G446">word</foreign>), </seg>
</etym>
  <sense>to be proconsul: <ref osisRef="Acts.18.12">Ac 18:12</ref> Rec. (v.s. <foreign xml:lang="grc">ἀνθύπατος</foreign>).†</sense>
</entry>
```

The normal usage of this construct seems to be to tag the foreign word and put the Strong's number in the `@n`. What seems needed here is a structure to refer to the entry.

At a future time, I will write a script to search for other examples of English tagged as `foreign`.

**Comment by dowens76** [comment]
This one deserves further reflection. I think originally DSAW used a script to add these Strong's number references, but the dictionary itself is not really keyed to Strong's (in its print version). I would like to see such references should refer to the entry by the Greek term, not a number. 

But most importantly we need to note that this markup issue should be addressed globally at some point. Thanks for pointing this out.

**Comment by destatez** [comment]
Chuck cleaned up all the foreign tag-pair issues with a script
