### ISSUE TITLE
Need to update list of contributors

### ISSUE THREAD

**Issue by cbearden** [translatable-exegetical-tools/Abbott-Smith#71]
In the `/TEI/teiHeader[1]/encodingDesc[1]` element, we need to add the names of all the new contributors (Dave Statezni, Chapel Presson, et al.) who don't need to remain anonymous.

**Comment by destatez** [comment]
Chapel, can you do a direct edit of the XML to add these? Otherwise can you provide me with a list of names so I can edit it?

**Comment by cpresson** [comment]
I can take care of it.

**Comment by cpresson** [comment]
Fixed with latest PR merge (#88)
