### ISSUE TITLE
Character too use for primes when Greek letters are cited as numerals

### ISSUE THREAD

**Issue by cbearden** [translatable-exegetical-tools/Abbott-Smith#8]
E.g. in the entry for the alpha:

```
<sense><gloss>alpha</gloss>, the first letter of the Greek alphabet. As a numeral, <foreign xml:lang="grc">ά</foreign> = 1,
```

Here the alpha has the tonos rather than the following prime; the beta in its entry has a simple apostrophe. We should use the same character throughout the dictionary.

**Comment by destatez** [comment]
I will investigate to see if there are any instancesbthat need correction

**Comment by destatez** [comment]
All but rho have been changed to use the apostrophe. Rho has not, but has a note about the fact that it is always accented as the first character of a word.
