### ISSUE TITLE
XML correctness of having 2 different n="Hxxxx" subclauses within one foreign tag-pair

### ISSUE THREAD

**Issue by destatez** [translatable-exegetical-tools/Abbott-Smith#86]
Our XML "Editor" / viewer flagged the instance of the subject line as an error. The XML line is shown in the attached file. Is this really an XML error? @cbearden 

[Possible_Issues.txt](https://github.com/translatable-exegetical-tools/Abbott-Smith/files/734405/Possible_Issues.txt)

**Comment by cbearden** [comment]
I’m afraid one of the rules of XML well-formedness is that you can have only one attribute with a particular name (e.g. ‘n’) per element, so you can’t have multiple ‘n’ attributes.

A number of other well-formedness errors have crept in, I’m afraid. I’m at work, so I don’t have time to review them all or where they were merged in.

I apologize if you already know this, but there are two levels of correctness in XML files, much like with program source code:

  * well-formedness, which is analogous to syntactic correctness in a C or Perl script;
  * conformity to or validity with respect to some notion of correct use of the markup in question, which is analogous to to making a syntactically correct program actually do what you want it to do; this level is often expressed in terms of a DTD or schema, but the notion of correct markup usage may be less formalized than that as well.

Just as a compiler will choke on C where statements aren’t terminated with semicolons, or on a Python program that isn’t correctly indented, an XML parser will refuse to parse a document that isn’t well-formed. So think of having multiple attributes with the same name on a single element as being like a Java ‘if’ statement that doesn’t enclose multiple conditional statements in the body in curly braces.

**Comment by destatez** [comment]
I updated the XML to combine the multiple n-values into a single n-value
