### ISSUE TITLE
How to tag subscripts after Bible books

### ISSUE THREAD

**Issue by cbearden** [translatable-exegetical-tools/Abbott-Smith#9]
The list of abbreviations in the PDF (p. XVI) says this about subscripted numbers after the names of Bible books:

> “An inferior numeral after a biblical book (e.g. III Mac 6) indicates the number of times a word occurs in that book.”
> So in the entry for 'ἀγών|G73', we have the following:
> 
> ```
> II Mac <hi rend="subscript">6</hi>, IV Mac <hi rend="subscript">5</hi>
> ```
> 
> Should we tag these also as `osisRef` elements? The above would become e.g.

```
<ref osisRef="2Macc">II Mac <hi rend="subscript">6</hi></ref>, <ref osisRef="4Macc">IV Mac <hi rend="subscript">5</hi></ref>
```

I've tagged a couple of instances this way before looking for precedents in what has already been tagged, but these should be easy to detect and change if we decide not to make them `osisRef` elements. I just haven't thought this through, and I don't know if it was decided already.

**Comment by dowens76** [comment]
Sorry for the slow response. Your markup suggestion sounds good to me.

**Comment by destatez** [comment]
I can do a search to find out how many subscripts are in the file which are related to a citation. If the count is small I can update the file for those, or otherwise I can generate a report that would be an issue for en-ugl so the ball is not dropped.

**Comment by destatez** [comment]
In reviewing all of the numbered subscripts, all but 2 are providing instance counts for entire books, and in many cases instances in a range of books. About half of these are to reference materials and not citations that we would provide links to, anyway. I will update the XML for these 2 cases where the instance counts are for chapters within Biblical texts.
